# Generated by Django 4.2.9 on 2024-03-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_1", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userquery",
            name="query",
        ),
        migrations.RemoveField(
            model_name="userquery",
            name="reply",
        ),
        migrations.AddField(
            model_name="userquery",
            name="instruction",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="userquery",
            name="output",
            field=models.TextField(default=""),
        ),
    ]
