# Generated by Django 4.2.9 on 2024-10-28 03:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("app_1", "0002_remove_userquery_query_remove_userquery_reply_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BGPTrafficTask",
            fields=[
                (
                    "task_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("asn", models.IntegerField()),
                ("target_prefixes", models.JSONField(blank=True, null=True)),
                ("collection_period_minutes", models.FloatField(default=2.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("media_dir", models.CharField(blank=True, max_length=255, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Book",
        ),
        migrations.RemoveField(
            model_name="playlistvideos",
            name="playlist",
        ),
        migrations.RemoveField(
            model_name="playlistvideos",
            name="video",
        ),
        migrations.DeleteModel(
            name="Userquery",
        ),
        migrations.RemoveField(
            model_name="video",
            name="plist",
        ),
        migrations.DeleteModel(
            name="Playlist",
        ),
        migrations.DeleteModel(
            name="Playlistvideos",
        ),
        migrations.DeleteModel(
            name="Video",
        ),
    ]
