# Generated by Django 4.2.9 on 2024-10-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_1", "0003_bgptraffictask_delete_book_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bgptraffictask",
            name="query",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bgptraffictask",
            name="session_id",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="bgptraffictask",
            name="asn",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="bgptraffictask",
            name="collection_period_minutes",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bgptraffictask",
            name="status",
            field=models.CharField(
                choices=[
                    ("STARTED", "Started"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("GENERATING", "Generating RAG Query Results"),
                    ("RAG_COMPLETED", "RAG Query Completed"),
                ],
                default="STARTED",
                max_length=20,
            ),
        ),
    ]
