version: '3.8'

services:
  web:
    environment:
      - DJANGO_SETTINGS_MODULE=project_1.settings.development

  fastapi:
    environment:
      - ENV=development

  nginx:
    ports:
      - "80:80"
