version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.daphne
    command: ["daphne", "-b", "0.0.0.0", "-p", "8001", "project_1.asgi:application"]
    volumes:
      - .:/app
    env_file:
      - .env
    expose:
      - "8001"
    # depends_on:
    #   - redis
    #   - db

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./staticfiles:/app/staticfiles:ro
      - ./media:/app/media:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    # depends_on:
    #   - web

  # db:
  #   image: postgres:13
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_DB=name
  #     - POSTGRES_USER=user
  #     - POSTGRES_PASSWORD=password

  # redis:
  #   image: redis:6-alpine
  #   ports:
  #     - "6379:6379"

# volumes:
#   postgres_data:
