version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.daphne
    volumes:
      - .:/app
    env_file:
      - .env
    expose:
      - "8001"
    # depends_on:
    #   - redis
    #   - db
  agent:
    build:
      context: .
      dockerfile: docker/Dockerfile.fastapi
    # ports:
    #   - "8000:8000"
    env_file:
      - .env
    expose:
      - "8000"
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./staticfiles:/app/staticfiles:ro
      - ./media:/app/media:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - agent
    
  # db:
  #   image: postgres:13
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_DB=name
  #     - POSTGRES_USER=user
  #     - POSTGRES_PASSWORD=password

  # redis:
  #   image: redis:6-alpine
  #   ports:
  #     - "6379:6379"

# volumes:
#   postgres_data:
